### ISSUE TITLE
Build crash with latest changes

### ISSUE THREAD

**Issue by bedryck** [defold/extension-spine#108]
Steps to reproduce:

1) Open a project with the latest spine extension
2) Try to Project-> Build

Errors that I have 
![image](https://user-images.githubusercontent.com/22659468/198143053-4fcd55e3-98eb-4611-80ff-aafdb57ef421.png)

I have this issue only in the latest changes ( [https://github.com/defold/extension-spine/compare/2.4.0...main](https://github.com/defold/extension-spine/compare/2.4.0...main) ), also pay attention I have errors where the changes were made. 

Build with these changes [https://github.com/defold/extension-spine/archive/refs/tags/2.3.1.zip](https://github.com/defold/extension-spine/archive/refs/tags/2.3.1.zip) works as expected.

Tell me if you need more information

**Comment by britzl** [comment]
@bedryck which version of Defold are you testing with?

**Comment by bedryck** [comment]
@britzl , 1.3.7
![image](https://user-images.githubusercontent.com/22659468/198286621-f8808e58-61e2-43a1-a9be-bfeb4dae4a8a.png)

**Comment by britzl** [comment]
Ok, yes, https://github.com/defold/extension-spine/releases/tag/2.3.1 supports Defold 1.3.7, just like you discovered too.

And the latest changes on `main` only supports Defold 1.3.8 as seen in the commit message.

**Comment by bedryck** [comment]
1.3.8 is still in beta. What do you suggest use https://github.com/defold/extension-spine/releases/tag/2.3.1 for 1.37?

**Comment by britzl** [comment]
> 1.3.8 is still in beta. What do you suggest use https://github.com/defold/extension-spine/releases/tag/2.3.1 for 1.37?

Yes!

**Comment by bedryck** [comment]
Thank you! I close a bug
