### ISSUE TITLE
Unable to Load Plugin (Editor Plugin)

### ISSUE THREAD

**Issue by ProtonGustave** [defold/extension-spine#115]
I've downloaded latest Linux build from website(1.4.1 editor-alpha e0ad4769ad5b83c60b185b54ff889f4437b0d128 8f96e450ddfb006a99aa134fdd373cace3760571)
Then added https://github.com/defold/extension-spine/archive/main.zip as a dependency and now i see this error on editor startup, what should i do? Not sure how to figure out correct version
![image](https://user-images.githubusercontent.com/35541456/214003777-5f5fdb8c-22fa-4425-9057-a0820b1ef98e.png)

**Comment by JCash** [comment]
Hi @ProtonGustave !

The main branch is for us when developing new features. And it's currently containing updates that are compatible with Defold 1.4.2.

I suggest you instead use one of the stable releases from here:
https://github.com/defold/extension-spine/releases

**Comment by ProtonGustave** [comment]
@JCash Thanks! It's fixed the issue
This guide suggested to use this archive https://defold.com/extension-spine/
