### ISSUE TITLE
bones rotation is not working

### ISSUE THREAD

**Issue by Sublustris** [defold/extension-spine#12]
In models imported from Spine4 bones are not rotating during the animation.

**Comment by AGulev** [comment]
Is it for the new runtime https://github.com/defold/extension-spine/tree/spine-runtime ?

**Comment by Sublustris** [comment]
> Is it for the new runtime https://github.com/defold/extension-spine/tree/spine-runtime ?

yes

**Comment by JCash** [comment]
HI @Sublustris , would it be possible for you to share a small repro case?

**Comment by JCash** [comment]
I've pushed a new fix in the `spine-runtime` branch which I believe was the root cause for this issue.

Note that the fix requires the latest version of the alpha editor.

**Comment by JCash** [comment]
@Sublustris Please let us know if this is now working for you.
