### ISSUE TITLE
Masks From Spine to defold

### ISSUE THREAD

**Issue by zarkua** [defold/extension-spine#120]
I`ve found GUI clipping function in defold and mask function in spine, but it seems that they are not connected for some reason. Is there any way to use masks from spine in defold?

**Comment by britzl** [comment]
It will be hard to get gui clipping and masks in Spine to work well together.

It should be much easier to get Spine masks to work in game objects.

**Comment by Jhonnyg** [comment]
Completed by https://github.com/defold/extension-spine/pull/173
