### ISSUE TITLE
Online Documentation appears incorrectly linked

### ISSUE THREAD

**Issue by wookieejedi** [defold/extension-spine#126]
Currently, the online documentation for the spine extension only shows gui related functions, and there is not even `spine.play_anim(` on the doc page anymore ([doc page here](https://defold.com/extension-spine/api/)).

The online documentation should show this page, too:
[https://github.com/defold/extension-spine/blob/main/defold-spine/api/spine.script_api](https://github.com/defold/extension-spine/blob/main/defold-spine/api/spine.script_api)

**Comment by britzl** [comment]
Fixed in https://github.com/defold/defold.github.io/commit/078dcfa5d4a6169240cc44a7c8fe23c0de245571 (live in ~10 mins)
