### ISSUE TITLE
Expose "playback rate" and "offset" to spine component

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/extension-spine#129]
**Use case:**
I have a large game scene which contains animated non-interactive objects. I would like to customize playback rate and start offset of each animation to differentiate object with same image

**What needed:**
Expose parameters "playback rate" and "offset" to spine component. Use values from it as initial values after component was created.
Also checkbox like "random offset" should be useful.

**Alternative way:**
Control such parameters via script (pass it to spine.play_anim).

**Comment by AGulev** [comment]
Sounds reasonable, but we are not going to implement "random offset" checkbox
