### ISSUE TITLE
Editor error when opening .spinejson

### ISSUE THREAD

**Issue by Morgerion** [defold/extension-spine#133]
### Expected behaviour
Normal installation of the .spinejson with no errors.

### Actual behaviour
The editor gives an error when trying to install the .spinejson.

### Steps to reproduce
[test_spine_model.zip](https://github.com/defold/extension-spine/files/11245074/test_spine_model.zip)
Add a spine-model from the archive to any project.
And be sure to try to create a spine-scene where you insert this spine-model.

<hr/>

<table>
<tr><td>Build time</td><td>2023-04-15T06:38:40.314856</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9819fb3293da0b08227ef01827816866ad6011f3</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8bdf04665ed54034bb112b93d892c510"'>8bdf04665ed54034bb112b93d892c510</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 200 Series</td></tr>
<tr><td>GPU Driver</td><td>4.6.14831 Compatibility Profile Context 21.5.2 27.20.20903.8001</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
https://user-images.githubusercontent.com/2209596/232401279-139998ce-6185-4d2c-8d15-99bba48ff788.mp4

Works fine for me. 
This spinejson is for spine 4.1, make sure you use the latest spine versions.

**Comment by Morgerion** [comment]
Thank you for your attention to my problem.
I restarted the PC and everything worked! :)
