### ISSUE TITLE
Property 'material' not found!

### ISSUE THREAD

**Issue by serj1024** [defold/extension-spine#141]
When attempting to get the "material" property of the #spinemodel component, an error occurs:

ERROR:SCRIPT: main/main.script:33: Property 'material' not found!
stack traceback:
  [C]:-1: in function get
  main/main.script:33: in function <main/main.script:27>

To reproduce, add the line: pprint(go.get(self.url, "material")) in the init() method in main.script.

![image](https://github.com/defold/extension-spine/assets/34648793/ac4bc92c-7249-47ce-af99-2135101808c6)

However, initially there was another problem. When changing the material at runtime: go.set(..., "material", ...), the following error occurs: (If the material is selected in advance, everything works fine.)

ERROR:RENDER: Failed to get material tag list with hash 0x00008b52

Defold version 1.4.8, Spine version 2.11.1.

**Comment by serj1024** [comment]
everything works fine in Defold version 1.4.1 (1.3.7), Spine version 2.5.0.

**Comment by abadonna** [comment]
Still not working- Defold 1.9.0, Spine 3.3.0
