### ISSUE TITLE
Issue with Spine Animation rendering as Yellow line in Defold

### ISSUE THREAD

**Issue by NighelNijhuis** [defold/extension-spine#150]
### Problem Description:
I'm encountering an issue where a Spine animation, exported as spinejson and integrated into Defold, is rendering as a strange yellow line when the game is booted up. A minimal project highlighting the problem is attached for reference.

### Steps to Reproduce:
>     Start the project
>     Run the game and observe the Spine animation rendering as a yellow line.

### Expected Behavior:
The Spine animation should render correctly within the Defold game without any distortions or color anomalies.

### Actual Behavior:
Upon starting the game, the Spine animation appears as a yellow line instead of the expected animation.

### Project Files:
[spine_animation_issue.zip](https://github.com/defold/extension-spine/files/13450277/spine_animation_issue.zip)

**Comment by britzl** [comment]
Please update to 2.13.0. That version contains a fix for issues with vertex formats, introduced in 1.6.1.

https://github.com/defold/extension-spine/releases/tag/2.13.0

<img width="843" alt="Screenshot 2023-11-23 at 15 58 51" src="https://github.com/defold/extension-spine/assets/1300688/590eafb6-d598-44cd-a819-9a234307a27e">
