### ISSUE TITLE
java.lang.ExceptionInInitializerError: Unknown java.lang.ClassNotFoundException: editor.spineext$eval2862$fn__2863

### ISSUE THREAD

**Issue by pkosmovskaya-ms** [defold/extension-spine#158]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-10-10T06:48:54.384007</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>aa5089a770bba1605be131cf46d32784dc37a597</td></tr>
<tr><td>Defold engine sha</td><td>aa5089a770bba1605be131cf46d32784dc37a597</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9086793942b94c58813a0940779effb2"'>9086793942b94c58813a0940779effb2</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.6.1</td></tr>
<table>

**Comment by britzl** [comment]
@pkosmovskaya-ms which version of the Spine extension are you using (check game.project, dependencies section)?

**Comment by pkosmovskaya-ms** [comment]
@britzl Hi, looks like this issue in not relevant as I was trying to do smth that is not supported by the project(switch to offline mode via game.project). when starting the build as usual - no such error.
extension-spine-20230821-ee3c378.zip
