### ISSUE TITLE
Build error with Defold 1.7+ release

### ISSUE THREAD

**Issue by zimbric** [defold/extension-spine#161]
Game fails to build after working previously. The following messages earned the red x in the build error report. I haven't filed an issue report before so let me know if there is anything I need to add. 
```
/defold-spine/src/gui_node_spine.cpp
	Line 709: no matching function for call to 'SetNodeTexture'
  709 |     dmGui::SetNodeTexture(node->m_GuiScene, node->m_GuiNode, dmGui::NODE_TEXTURE_TYPE_TEXTURE_SET, node->m_SpineScene->m_TextureSet);
```

```
/defold-spine/src/gui_node_spine.cpp
	Line 851: no matching function for call to 'SetNodeTexture'
  851 |         dmGui::SetNodeTexture(node->m_GuiScene, node->m_GuiNode, dmGui::NODE_TEXTURE_TYPE_TEXTURE_SET, node->m_SpineScene->m_TextureSet);
```

**Comment by AGulev** [comment]
Do you use the latest version of spine ext? https://github.com/defold/extension-spine/releases/tag/2.14.5

**Comment by zimbric** [comment]
Yes, I am using release 2.14.5 with the following link pasted into my dependencies: https://github.com/defold/extension-spine/archive/refs/tags/2.14.5.zip

I tried using a few earlier versions as well but they all give the same results. I am just learning Defold so let me know if there is something simple that I may have overlooked. Thank you!

**Comment by AGulev** [comment]
When you are updating a link in dependency to have to fetch changes: 
![CleanShot 2024-03-17 at 13 22 51@2x](https://github.com/defold/extension-spine/assets/2209596/35c254c3-254a-4786-9ae6-02ff9c9a9758)
(or restart the editor)

it doesn't make sense to check older versions, only 2.14.5 one is comparable with 1.7.0

**Comment by zimbric** [comment]
I did restart the editor but i did not know about fetching libraries. With that step it is working now.

I appreciate your patience, I am just learning. Thank you for your support.

**Comment by AGulev** [comment]
> I appreciate your patience, I am just learning. Thank you for your support.

It's fine, we were all there.
I'm closing this issue
