### ISSUE TITLE
Any plan to support spine 4.2 stable ?

### ISSUE THREAD

**Issue by arywindows** [defold/extension-spine#166]
Hi spine 4.2 stable has been released, is there any plan to support the runtime?

Thank you

**Comment by AGulev** [comment]
I answered here https://forum.defold.com/t/how-to-update-extension-spine-runtime-to-4-2-beta/76325/4?u=agulev

> No, I don’t think it will be added any time soon, unless someone decides to implement it (it’s [an open-source extension](https://github.com/defold/extension-spine), so anyone can contribute) or a company that wants to use it decides to sponsor such an update.

> I don’t want to create false expectations: internally, our team does not have any plans to do so.

**Comment by badlogic** [comment]
See https://github.com/defold/extension-spine/pull/167

**Comment by arywindows** [comment]
Hi!

I'm just wondering is there any update about the 4.2 runtime?

Thank you

**Comment by britzl** [comment]
There is an active pr here: https://github.com/defold/extension-spine/pull/167

**Comment by britzl** [comment]
Closed by https://github.com/defold/extension-spine/commit/b231686af15a43cb08b46f602e0ccd113f8d7224
