### ISSUE TITLE
spine.play_anim doesn't work in version 3.2.0

### ISSUE THREAD

**Issue by sergeysinyavsky** [defold/extension-spine#176]
### Actual behaviour

I get an error when I call:

        spine.play_anim("/go#finger", "finger_tap", go.PLAYBACK_NONE)

Error:

        INFO:DLIB: Log server started on port 56165
        INFO:ENGINE: Target listening with name: SSV-PC - 192.168.1.11 - Windows
        INFO:ENGINE: Engine service started on port 56166
        INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
        INFO:ENGINE: Defold Engine 1.8.1 (fd1ad4c)
        INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
        INFO:ENGINE: Loading data from: build/default
        INFO:SPINEEXT: Registered spine extension
        
        INFO:ENGINE: Initialised sound device 'default'
        Assertion failed: i < Size(), file /var/extender/sdk/fd1ad4c17bfdcd890ea7176f2672c35102384419/defoldsdk//sdk/include/dmsdk/dlib/array.h, line 487
        INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\Sergey\AppData\Roaming\Defold/_crash
        ERROR:CRASH: CALL STACK:
        
        ERROR:CRASH:  0 0x7FF695199BF0 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
        ERROR:CRASH:  1 0x7FF695557C14 raise /tmp/job7513950873880048019/minkernel/crts/ucrt/src/appcrt/misc/signal.cpp:547
        ERROR:CRASH:  2 0x7FF695548310 abort /tmp/job7513950873880048019/minkernel/crts/ucrt/src/appcrt/startup/abort.cpp:71
        ERROR:CRASH:  3 0x7FF6955475F4 common_assert_to_stderr<wchar_t> /tmp/job7513950873880048019/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:186
        ERROR:CRASH:  4 0x7FF69554710C _wassert /tmp/job7513950873880048019/minkernel/crts/ucrt/src/appcrt/startup/assert.cpp:443
        ERROR:CRASH:  5 0x7FF6950E72E0 dmSpine::CompSpineModelGetComponent /tmp/job7513950873880048019/upload/defold-spine/src/comp_spine_model.cpp:269
        ERROR:CRASH:  6 0x7FF695201390 dmGameObject::GetComponentUserDataFromLua D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject_script.cpp:512
        ERROR:CRASH:  7 0x7FF695270270 dmScript::GetComponentFromLua D:\a\defold\defold\engine\gamesys\src\gamesys\gamesys_script.cpp:114
        ERROR:CRASH:  8 0x7FF6950F2C60 dmSpine::SpineComp_PlayAnim /tmp/job7513950873880048019/upload/defold-spine/src/script_spine.cpp:280
        ERROR:CRASH:  9 0x7FF6950F8A3E lj_BC_FUNCC <unknown>:0
        ERROR:CRASH: 10 0x7FF695191120 lua_pcall <unknown>:0
        ERROR:CRASH: 11 0x7FF6951C30F0 dmScript::PCallInternal D:\a\defold\defold\engine\script\src\script.cpp:1401
        ERROR:CRASH: 12 0x7FF695228E60 dmGameObject::RunScript D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:142
        ERROR:CRASH: 13 0x7FF695227700 dmGameObject::CompScriptInit D:\a\defold\defold\engine\gameobject\src\gameobject\comp_script.cpp:183
        ERROR:CRASH: 14 0x7FF6951FA1C0 dmGameObject::InitComponents D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:1704
        ERROR:CRASH: 15 0x7FF6951F6A20 dmGameObject::InitCollection D:\a\defold\defold\engine\gameobject\src\gameobject\gameobject.cpp:1773
        ERROR:CRASH: 16 0x7FF69527AC20 dmEngine::Init D:\a\defold\defold\engine\engine\src\engine.cpp:1348
        ERROR:CRASH: 17 0x7FF695279B60 dmEngineCreate D:\a\defold\defold\engine\engine\src\engine.cpp:2160
        ERROR:CRASH: 18 0x7FF69527F880 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:68
        ERROR:CRASH: 19 0x7FF6951874C0 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
        ERROR:CRASH: 20 0x7FF6955010F4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
        ERROR:CRASH: 21 0x7FFE96B27330 BaseThreadInitThunk <unknown>:0
        ERROR:CRASH: 22 0x7FFE973E2690 RtlUserThreadStart <unknown>:0
        ERROR:CRASH: Lua Callstack:
        ERROR:CRASH:   main/main.script:2: in function <main/main.script:1>
        ERROR:CRASH: 

### Steps to reproduce
[Bug.zip](https://github.com/defold/extension-spine/files/15496571/Bug.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-28T14:20:53.141474</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7247f038fba6f40cda23c5ea2e38e9fde69a2ea6</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.11.1.231017</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jhonnyg** [comment]
You will have to use 1.8.2, apparently spine now relies on a critical bugfix that was added into 1.8.2. The release have been renamed to reflect this change.
