### ISSUE TITLE
Mesh based IK animations currently broken

### ISSUE THREAD

**Issue by subsoap** [defold/extension-spine#19]
This example used to work
[SpineMeshIKAnimation.zip](https://github.com/defold/extension-spine/files/7969054/SpineMeshIKAnimation.zip)

Older version of the example which 100% worked in older versions
[WebSpineJiggleIK_physically_based.zip](https://github.com/defold/extension-spine/files/7969055/WebSpineJiggleIK_physically_based.zip)

**Comment by JCash** [comment]
Fixed in https://github.com/defold/extension-spine/releases/tag/1.2.2

(We used the wrong target url)
