### ISSUE TITLE
Preview Spine animations (DEFEDIT-683)

### ISSUE THREAD

**Issue by britzl** [defold/extension-spine#23]
Description:
When in a *.spinescene I want the ability to preview the different animations. This would be helpful even in *.go, *.collection, and *.gui

Use case:
User want to see how the spine animation looks in the engine

2017-01-11 14:28:07 (Sara.Cederberg)
Ragnar: We have not yet added spine animation previewing to Editor2 at all, but when we do we should fix it for spine scenes as well.

**Comment by JCash** [comment]
Fixed in 1.3.0
