### ISSUE TITLE
Use blend modes defined in Spine (DEF-2400)

### ISSUE THREAD

**Issue by britzl** [defold/extension-spine#36]
Description:
There should be a SpineModel BlendMode setting to respect the blend modes defined in a Spine file instead of overriding it with one mode for the whole thing.

Currently the blend mode can be set on a SpineModel which is fine in some cases. The problem is when a Spine has some parts that should be rendered with Add and some other parts that should be Alpha blended. What you need to do in those cases is to split it up into multiple animations and Spine files, set up one SpineModel for each blend layer (making sure it's rendered in the right order) and play the animations in sync.
A much better workflow would be to create just one Spine file that has the blend modes defined. Then a single SpineModel could be set up with the blend mode to "Spine" or something similar. Each Spine sub mesh would be rendered with the blend mode defined in the Spine file.

Use case:
Since there is no option not to override the blend modes defined in a Spine file we have to split up the animations across multiple files. This is a very bad workflow for artists, since you can't see the whole animation in the Spine editor. It also limits how many blend layers you can use without it getting too difficult to manage.

Business need:
Adding this feature would save us time and make it possible to do more complex Spine animations of higher quality.
2017-02-16 08:06:40 (Halldor.Bjarnason)
I would like to add that with the current workaround the 'add' blending mode layers obviously can not be in different depths of the animation, they are always in the front or in the back of the whole thing.

**Comment by AGulev** [comment]
example project is avaliable here https://github.com/defold/extension-spine/issues/125

**Comment by britzl** [comment]
https://esotericsoftware.com/spine-slots#Blending
