### ISSUE TITLE
Error when building bundle for android(`libSpineExt.dll`)

### ISSUE THREAD

**Issue by sergeysinyavsky** [defold/extension-spine#64]
I get this error when building a bundle from editor on android.

    /defold-spine/plugins/lib/x86_64-win32/libSpineExt.dll
	E:\Projects\PotatoJam\spine_offset\build\plugins\defold-spine\plugins\lib\x86_64-win32\libSpineExt.dll (The process cannot access the file because it is being used by another process)
    
[spine_offset.zip](https://github.com/defold/extension-spine/files/8222949/spine_offset.zip)

<table>
<tr><td>Build time</td><td>2022-03-08T12:35:13.609680</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c281f9bace40f3d2e6a56d5b515601e92f5ab9ad</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by sergeysinyavsky** [comment]
This dll is processed when the editor starts
![image](https://user-images.githubusercontent.com/12486956/157678859-1f64bdbf-0f81-4172-b735-093fe5227e22.png)

**Comment by sergeysinyavsky** [comment]
I noticed that the bundle is also not built for other platforms

**Comment by leha-games** [comment]
I'm also have this issue. Can't bundle for any platform with Spine extension on Windows 10.

`libSpineExt.dll (The process cannot access the file because it is being used by another process)`

**Comment by JCash** [comment]
As a workaround, you can remove the folder `./build/plugins` in you project, and it will then be able to copy the files.

**Comment by leha-games** [comment]
@JCash In latest Defold 1.3.1 alpha release I can successfully build bundles on Windows 10. Thanks!
