### ISSUE TITLE
Wrong animation_id in callback during blend, later callback not sent

### ISSUE THREAD

**Issue by dri-richard** [defold/extension-spine#72]
If a one-shot animation (PLAYBACK_ONCE_FORWARD) is played towards the end of a looping animation, with a blend such that a loop of the first animation occurs during the blend, the wrong animation_id is passed in the callback and subsequent play_anim calls behave unexpectedly.

I've reproduced this in the example (see below for attachment) with the following changes:
1. The idle animation is played by itself with no aiming/IK :
`spine.play_anim(self.url, "idle", go.PLAYBACK_LOOP_FORWARD)`
2. The death animation is played with a blend when clicking the mouse
`spine.play_anim(self.url, "death", go.PLAYBACK_ONCE_FORWARD, { blend_duration = 0.5  }, callback)`
3. The callback plays the idle animation again when the death animation completes - this is similar to the behaviour in our game which worked with the old runtime, but not now
```
if message_id == hash("spine_animation_done") and message.animation_id == hash("death") then
	spine.play_anim(self.url, "idle", go.PLAYBACK_LOOP_FORWARD, { })
end
```
To reproduce:
1. Replace main.script in the example with the attached version.
2. When the character is raising the gun, at about the midway point, click the mouse. The current cursor value is printed - the bug occurs when the cursor is a high value / towards the end of the idle animation.
3. Wait for the end of the death animation
4. If the animation_id printed to the console by the callback is hash: [death], then the idle anim will correctly start.
5. If the animation id is hash: [idle], then the bug has been reproduced. The callback was incorrectly called for the idle animation, and then you will also see that the spine_animation_done message was wrongly sent for the death animation, and handled by on_message .
[main.zip](https://github.com/defold/extension-spine/files/8411914/main.zip)

**Comment by d954mas** [comment]
Yes, something wrong. Also have problem that look the same.

**Comment by zitzitz** [comment]
Same problem. Any news or solutions?

**Comment by d954mas** [comment]
@britzl looks like annoying issues that make it impossible to use callbacks(

Please look on it

**Comment by britzl** [comment]
> Please look on it

@JCash will take a look.
